table dim_date
	lineageTag: c681a127-5757-4dbe-b04d-68f8a496581d
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e56119b9-de1e-4f73-838a-b43cc51b3a4e
		summarizeBy: none
		sourceColumn: date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 814df16a-b20b-4d24-ab1b-d0751861ae66
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 1160e054-60b2-4245-8d1d-0211f4b45691
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 11066041-16ca-4fe5-a416-094d4006b3ae
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 4c6217f0-c0eb-4f7c-a3bd-0fc6b904d8c6
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 016dc878-5324-4531-a190-77366a30b234
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: 56a9a4d7-7d94-434e-a4e0-98638e611bce
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		formatString: 0
		lineageTag: 96234452-c148-44d7-a264-4472d5079adf
		summarizeBy: sum
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column is_weekday
		dataType: int64
		formatString: 0
		lineageTag: 8eaf1955-a237-4e8b-8c8a-fdba216d1bfc
		summarizeBy: sum
		sourceColumn: is_weekday

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\TUKU MAPA\Documents\Project\insurance_performance_powerBI\data\dim_date.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"fiscal_year", Int64.Type}, {"fiscal_quarter", Int64.Type}, {"is_weekday", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

